project:
  type: book
  output-dir: docs


book:
  title: "Bayesian Analysis with Python: Notebook"
  author: "Norah Jones"
  date: "7/30/2025"
  chapters:
    - index.qmd
    - thinking-probabilistically.qmd
    - Programming-Probabilistically.qmd
    - mlm.qmd
    - multiple-regression.qmd
    - references.qmd

jupyter: python3

format:
  html:
    theme:
      - cosmo
      - brand




